# Generated by Django 3.2.5 on 2022-07-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, default='_static/user_resources/default.txt/', upload_to='user_resources/'),
        ),
    ]
