# Generated by Django 3.2.5 on 2022-07-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0002_resource_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to='user_resources/'),
        ),
    ]
